### ISSUE TITLE
Cannot find 'xxx' reference in __init__.py

### ISSUE THREAD

**Issue by PingYiwei** [zhuminjie/OpenSeesPyDoc#196] opened 2020-07-27 08:46 UTC
Greetings,
I come again. When I use 0.5.3 version with the system python3.7 interpreter, everything is ok. However, when I use the latest version (3.2.2.1), there is a warning: cannot find 'xxx' reference in __init__.py.
By the way, if I use anaconda3, this problem may occur sometimes. This problem could be solved by add the anaconda3 path to the system environment varible, but it can not work every time. Could you give some advice about this problem and tell me the reason, Thanks a lot!

**Comment by zhuminjie** [comment] 2020-07-27 18:11
You are on WIndows or LInux?

**Comment by PingYiwei** [comment] 2020-07-28 01:48
> You are on WIndows or LInux?

I am on Windows 10.

**Comment by zhuminjie** [comment] 2020-07-28 17:29
what is the 'xxx'

**Comment by mhscott** [comment] 2020-07-28 17:33
Can you post a screenshot, @PingYiwei ?

**Comment by PingYiwei** [comment] 2020-07-29 05:12
> what is the 'xxx'

‘xxx’ means very function or modulus in opensees, such as  wipe, model, element and so on. I use the pycharm to write and run the codes. I didn't change any settings when I upgrade the version, and it can run after upgrading but show the warning as I 
description above.

**Comment by PingYiwei** [comment] 2020-07-29 05:20
> Can you post a screenshot, @PingYiwei ?

sorry, i dont have the screenshot now, i run my code in 0.5.3, it works. The warning is "Can not find reference "wipe"  in __init__.py. I guess that there was some problem with pycharm, because when i use Command or jupyter notebook, there was no warning occurring.

**Comment by zhuminjie** [comment] 2020-07-29 19:22
It sounds that the problem is with pycharm. I cannot know the reason for pycharm. When do you have the warnings, in import, or calling the function?

**Comment by PingYiwei** [comment] 2020-07-30 04:03
> It sounds that the problem is with pycharm. I cannot know the reason for pycharm. When do you have the warnings, in import, or calling the function?

calling the function. I read the __init__.py in different openseespy version, and find that there are some differences between them.

**Comment by zhuminjie** [comment] 2020-07-30 21:59
The fact is the the init.py is only called once when you import openseespy. It's better you can give some screen shots so we can take a look.

**Comment by mhscott** [comment] 2022-06-12 14:58
Closing. Re-open if you are able to provide more information of let us know if you have resolved the issue.

**Closed by mhscott** 2022-06-12 14:58 UTC
